spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t9VEDQLXehvq5dTmgMo
      secret-key: U4RF9yEPQkEDCtvKmNFuH9KrRhtULS
      oss:
        endpoint: oss-us-east-1.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.56.10
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true
      cache-null-values: true
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 9090

logging:
  level:
    com.atguigu.gulimall: error

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
