spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
  redis:
    host: 192.168.56.10
    port: 6379
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    publisher-confirms: true # 开启发送端确认模式
    publisher-returns: true # 开启发送端消息抵达队列的确认模式
    template:
      mandatory: true # 只要抵达队列，以异步发送优先回调我们这个returnconfirm
    listener:
      simple:
        acknowledge-mode: manual # 手动ack消息确认
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

#支付宝相关配置
alipay:
  app-id: 2021000117686103
  merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCn+lo9za3AyMtQQYGLgvczNioL/fvo4LqbGtIIAIVIA2dlQQq24LaH/Z1StV84LyI0oTYBCe5RUVxcseWkTc9okOxDWnxMxBgYw4rsoEAvk4q3q2ZEPN9yZJKUMxYRhuUv9hP7V/95vUN2jZC25KOIwpRw2Z7LpZKB/5R8GntOfqlt0jZGBFtSjIaDYpMAm4CnFvq8QwfCJQ2cPxdXrE+L8x3C3RgbAdGg/3v+PQ+tGKuPOIitEjzb1SaA6L49cJGT+FYw6Ble9+CDvch+BLu5k4AgnniGewSWhy/TVM8ZoMFGDntjvh6r8T7ZYaBIU1dYIoROkFRWccQrQojbIRU3AgMBAAECggEAXfk5Mwo2AnxTAfsjtiD2mrfangrhO08+FjfS+JcR+U+uMH9KtzTP6RSBRxwgwRXdVQQ7ailcIjIaMeF0T48YUa+B/cxJbcjmkjQTLH4aaoNoP4isFdDYUO7i8fYCipuk7EgGtb5tNnYjn9di9m7C7metE9UreVKPvBp3v1YxVZ+qpNRq6EA+Grcpv9NgTPkftlk1CgMRTxryFbKlym3XQzUntANjiEV3QqSASXru8ZCh31ghQxtOJrhRzUOHuodSVGt16sBilTSOOv1M8scO9Dv98eLoxV1NMumbSYHcjI8d9xJ2q4F7BjH+q6OSxNutsBYbtq0OV/Jk69VX5PsJgQKBgQD58D4y3FNcaWnv4fef3yv3BVLPwnYKnV/gLjV47AEFVwv13rQazhT98T7sHm7C3ctt3nKa5c+hNpkGC2+VPmpvBCWCncWUORbndJ1+kXrizuvEkYnZfatGJlcTnD3lq8fqyv0ZUgS7ApbmT8KyP/kG8Vp2+FtIf1vW/FxVO4iPzwKBgQCsDUDJLPN6nemjJmGe1mha4cYZaeiBArj98g3lRQuiWB5vfmuFLc4NVPSoWrppUnXwGmNHPcKgi/9ZVv48gSATSUofx0NFmQJogAwuGxi4uBUk+po3ai+/OACkmaTctFCjDC+Bswr0AJ/3sf2tWGi1MzKMRRvuQYwIkPib5SzWGQKBgG1KCNiSkPz6tzEGnRHSM1ZLhJ+GR7lygUb0zbr3b6bXHkq/u/9wl6tG/x2eXQ5mj5qWR4TF8plq11TWUU9wQHgU1xYbSRb8M7C3xFpg4NwmYN/OR/nLQsZk43SWwFYaXEulwTB+NcVUZ4mD3P22jXzksosNJFU6I32JUhKO+rLvAoGABCUxmWc+2oZxeZ/UHEqYKxBjgHs/wdP59wxc71gxhpDO8uq91nCbFVElr+S3tw/ojYdlOvMu/EVDOrjQ2U5XIn/SjF91rHiaSUBEitvWRaURxVlQW+NwERBdW5nkEfk6NCN4BYz1x5k4QXSFYybNJwh7wEtt99iWciJkCwWDhgkCgYEAxIQMfJYsDaA/gy5Q08qLvQDsT5QkLUTd9djhsvbE5ooLsJpRjI7DzSHo6fQmPzIoQsqUI48wmsiymi0+hrDJjBmiaaX+uMS2ocV8FVVwitxd5et05Q/2X/66ouHiFpkBKHukAqqJKvBLjmjL/+M36qM6tn2iZsfdfV04kCarDQc=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj+F24QSlB4cF7NU+SxJL7nOEoS86kOqThAnU4AedQYyclgD/AdlrurOj/2TBw+Fdn3Go4txd8ANm0KQCUtWhMzV+5D3VN5S1LXOidYXF4zraco5slcRNC/cFlInacOZLCFWfThUtGVXIFPO2mIoLb9DnBjeJyqop73CgPL95scyNOYqKCzYuvy10vR8dJL6shx5P+JTIfd8I2tADTGRKAitpa3wny/mAYMsXJUshBi97roKAm5GEzbbKZ/yE0FY90omzXA6EIqQI1HXjELmvYA1C0LZ09zWzdNx6PwQrJHGqGOsd3ebREySMCYpjQrUI7MwrdB08eRNnQpljKN6K+wIDAQAB
  notify-url: http://3w3og6u9cw.51same.vip/payed/notify
  return-url: http://member.gulimall.com/memberOrder.html